### ISSUE TITLE
Need for an opam release (coq-bignums.8.9.0)

### ISSUE THREAD

**Issue by erikmd** [coq/bignums#17]
Dear coq-bignums maintainers,

As `coq.8.9.0` is now available in opam's default repository, could you prepare a compatible package for `coq-bignums` in *released*?

Indeed this is blocking for preparing a corresponding Docker image, and replace `coqorg/coq:8.9-beta1` with `coqorg/coq:8.9.0` on Docker Hub (cf. the related [docker-coq wiki](https://github.com/coq-community/docker-coq/wiki#supported-tags)).

The bignums repo does not contain a `v8.9` branch but I've checked the `v8.8` branch (as well as the `V8.8.0` tag) still compile with `coq.8.9.0`:
```
opam install coq.8.9.0
opam repository add coq-extra-dev https://coq.inria.fr/opam/extra-dev
opam install coq-bignums.8.8.dev  # ok
opam install --ignore-constraints-on=coq coq-bignums.8.8.0  # ok
```

Still, although it could suffice to relax the constraint of `coq-bignums.8.8.0` in `released` to also accept `coq.8.9.0`, given the naming convention chosen up to now in *released*:
```
opam show coq-bignums | grep all-versions
all-versions           8.6.0  8.7.0  8.8.0
```
I suspect it'd be preferable to:
* create a `v8.9` branch from 649dad440287151fd1937defb852886f192b8820,
* a tag `V8.9.0,`
* and a separated opam package `coq-bignums.8.9.0` in `released` (?)

Thanks!

**Comment by erikmd** [comment]
Hi @thery @letouzey @herbelin @Zimmi48 @mattam82 @maximedenes @silene @ppedrot @ejgallego @vbgl @gares,
(sorry for the noise! but I didn't know who I had to ping for that request coq/bignums#17 :)

To sum up, even if `coq-bignums` is now outside the Coq standard library, it appeared necessary to keep `BigN/BigZ/BigQ` available in all `coqorg/coq` Docker images (whose design has been discussed in coq/coq#7753, including images for Coq 8.4, 8.5 where `bignums` was bundled in the `coq` package)

**Comment by fblanqui** [comment]
Hi. I support Erik's post. I also need the version 8.9 for compiling CoLoR. When do you plan to release it?

**Comment by silene** [comment]
@fblanqui It is on the way. See coq/opam-coq-archive#568

**Comment by erikmd** [comment]
Thanks @silene, closing this issue.

**Comment by erikmd** [comment]
The `coqorg/coq:8.9.0` image is ready so that one can do `docker run --rm -it coqorg/coq:8.9.0`.  
(while the build of `mathcomp/mathcomp:1.7.0-coq-8.9` is still in progress)

BTW to document the need for this package in upcoming Docker images (for Coq `> 8.9.0`), would you agree to add one related item in
https://github.com/coq/coq/blob/master/dev/doc/release-process.md#these-steps-are-the-same-for-all-releases-beta-final-patch-level ?

e.g. something like that?

- Send an e-mail on Coqdev announcing that the tag has been put so that package managers can start preparing package updates (including a `coq-bignums` compatible version)
- Ping @erikmd to update the Docker images in `coqorg/coq` (requires `coq-bignums` in `extra-dev` for a beta / in `released` for a final release)  

Cc @Zimmi48 @ejgallego WDYT?

**Comment by Zimmi48** [comment]
Sure, feel free to open a PR.

**Comment by ejgallego** [comment]
Sounds great, thanks again @erikmd
