### ISSUE TITLE
  Need for a new release (coq-bignums.8.10.0)

### ISSUE THREAD

**Issue by erikmd** [coq/bignums#24]
Dear coq-bignums maintainers,

`coq.8.10.0` is now available in https://github.com/ocaml/opam-repository
but `coq-bignums.8.10.0` is not yet part of https://github.com/coq/opam-coq-archive

Please could you make a new release of bignums ?

(if it helps, I'll be able to open a PR in https://github.com/coq/opam-coq-archive then)

___

Related: https://github.com/coq-community/docker-coq/issues/2

**Comment by Zimmi48** [comment]
Hi @erikmd. Sorry again for these hurdles. It would seem that the best solution in the future will be to move back the bignums sources under the Coq repository (but keeping it a separate opam package probably) since it has appeared that people just stopped caring about bignums as soon as it was split.

In the meantime, I'd gladly give you write-access to this repository so that you can create tags yourself if that can help.

For the particular concern of creating the 8.10.0 Docker image, what is the issue with using the V8.10+beta1 tag in bignums? That it is not in coq-released and would be confusing if it were added there?

**Comment by erikmd** [comment]
Hi @Zimmi48, thanks for your comment

> It would seem that the best solution in the future will be to move back the bignums sources under the Coq repository (but keeping it a separate opam package probably) since it has appeared that people just stopped caring about bignums as soon as it was split.

OK, sounds like a good idea indeed!
(i.e., come back to a kind of "monorepo" but publish the packages apart)

> In the meantime, I'd gladly give you write-access to this repository so that you can create tags yourself if that can help.

Thanks for proposing, yes it could help :)

> For the particular concern of creating the 8.10.0 Docker image, what is the issue with using the V8.10+beta1 tag in bignums? That it is not in coq-released and would be confusing if it were added there?

Exactly: even if it is just a matter of convention, regarding the choice of the "stable" git tag of bignums associated with Coq 8.10.0 in the coq-released opam repo, IMHO a dedicated tag `V8.10.0` (and a release item in GitHub) would be less confusing than reusing the `V8.10+beta1` tag ;)
What do you think?

**Comment by Zimmi48** [comment]
>  What do you think?

I just wish we did not start using the same scheme for versioning Coq and packages depending on it in the first place :disappointed: 

Anyway, you should now have write-access, so feel free to create tags as you judge necessary.

**Comment by erikmd** [comment]
Hi @Zimmi48,
[sorry for the delay]

Here is a recap of what I've just done:
* I pushed an annotated (signed) tag `V8.10.0`
* I pushed two branches `v8.9` and `v8.10` to track the tags `V8.9.0` and `V8.10.0` (and these branches will be useful if one wishes to add the associated packages in [extra-dev](https://github.com/coq/opam-coq-archive/tree/master/extra-dev/packages/coq-bignums) as well)
* and I turned the annotated tag into a Github release.

Regarding the choice of the commit for `V8.10.0` it happens that the very next PR that had been merged after `V8.10+beta1` sounded useful to have (it was Maxime's backward-compatible fix #19, for Bignums not to rely anymore on the `Export` bug; I tested it locally with `coq.8.10.0` and current `coqorg/coq:dev`) 

so the new tag **`V8.10.0`** points to 33ae5d535509a3f8deee5808c9323491e98cc450

(I'll now open the associated PR in `opam-coq-archive`)

**Comment by erikmd** [comment]
PR coq/opam-coq-archive#957 is now merged so I close this issue (and relaunch the `coqorg/coq` build)

**Comment by Zimmi48** [comment]
Thanks a lot @erikmd!
