### ISSUE TITLE
New branch for coq-bignums.8.11.dev

### ISSUE THREAD

**Issue by erikmd** [coq/bignums#28]
Hi, to implement coq-community/docker-coq#3 I'll prepare a PR to to add `coq-bignums.8.11.dev` in
https://github.com/coq/opam-coq-archive/tree/master/extra-dev/packages/coq-bignums

However there is currently no v8.11 branch in https://github.com/coq/bignums/branches

@vbgl @maximedenes @Zimmi48 I can create that branch if you want, but before that could one of you confirm you're OK with selecting the last commit of master (a5dfe68b322bd40851fb0393f697811f4d1ef03b) as the tip of this branch?

**Comment by Zimmi48** [comment]
If this last commit does build with 8.11, then yes, this is the one that should be selected.

**Comment by erikmd** [comment]
Done in PR coq/opam-coq-archive#1017

**Comment by ppedrot** [comment]
@erikmd Can you open a v8.11 PR to use this branch on the Coq v8.11 CI?

**Comment by erikmd** [comment]
Hi @ppedrot , done (https://github.com/coq/coq/pull/11139)
