### ISSUE TITLE
Clarify exact license in repo and packages

### ISSUE THREAD

**Issue by palmskog** [coq/bignums#45]
We are trying to use [SPDX](https://spdx.org/licenses/) identifiers everywhere for licenses, which does not include "LGPL-2.1" - the possibilities are either `LGPL-2.1-only` or `LGPL-2.1-or-later`. This project should clarify in its README.md (and `meta.yml`) which one it is.

From 02fd659b34b6c9278d59af3f4f7ee45a988bd63d it seems the intent was to follow Coq's license, which is `LGPL-2.1-only`.

**Comment by erikmd** [comment]
Related: https://github.com/coq/opam-coq-archive/pull/1346
