### ISSUE TITLE
Circular dependency between `Make` and `Makefile.coq`

### ISSUE THREAD

**Issue by maximedenes** [coq/bignums#5]
There is some obvious circularity in the `Makefile` of Bignums.

**Comment by maximedenes** [comment]
@pletouzey, would you mind having a look? We are preparing Coq binary packages that include bignums for 8.8+beta1. Thanks!

**Comment by letouzey** [comment]
Should be fixed now, see commit 3b6b92ad

**Comment by maximedenes** [comment]
Thanks!
