### ISSUE TITLE
`Make` should be `_CoqProject`

### ISSUE THREAD

**Issue by maximedenes** [coq/bignums#6]
...so that we can edit files from Bignums under CoqIDE without having to manually set options.

**Comment by letouzey** [comment]
Hi @maximedenes, I'll do it, but note that you normally have write access to this repo, so for this kind of stuff, be my guest :smile:

**Comment by maximedenes** [comment]
Sure, I'm asking just because I have a pile of things to do for the release. In normal times, I would have sent a patch.

**Comment by letouzey** [comment]
fixed by 144281c

**Comment by maximedenes** [comment]
Thanks!
